class RegionMatch {

    matchRegion(meterRegion, vmRegion) {
        return regionTable[meterRegion] == vmRegion;
    }
}

module.exports = new RegionMatch();

const regionTable = {
    "ZA North": "southafricanorth",
    "DE North": "germanynorth",
    "US East 2": "eastus2",
    "US East 2": "eastus2",
    "CH West": "switzerlandwest",
    "CH West": "switzerlandwest",
    "AU Southeast": "australiasoutheast",
    "NO West": "norwaywest",
    "BR Southeast": "brazilsoutheast",
    "AE North": "uaenorth",
    "AU Central": "australiacentral",
    "FR Central": "francecentral",
    "US South Central": "southcentralus",
    "US South Central": "southcentralus",
    "EU West": "westeurope",
    "EU West": "westeurope",
    "US East": "eastus",
    "US East": "eastus",
    "US West Central": "westcentralus",
    "US West Central": "westcentralus",
    "CH North": "switzerlandnorth",
    "CA East": "canadaeast",
    "US West": "westus", "US West": "westus",
    "IN West": "westindia",
    "IN West": "westindia",
    "JA East": "japaneast",
    "JA East": "japaneast",
    "DE West Central": "germanywestcentral",
    "UK West": "ukwest", "UK West": "ukwest",
    "US West Central": "westcentralus",
    "CH West": "switzerlandwest",
    "BR South": "brazilsouth",
    "BR South": "brazilsouth",
    "JA West": "japanwest",
    "IN West": "westindia",
    "ZA North": "southafricanorth",
    "ZA North": "southafricanorth",
    "US North Central": "northcentralus",
    "US North Central": "northcentralus",
    "AU Central 2": "australiacentral2",
    "IN South": "southindia",
    "IN South": "southindia",
    "AU East": "australiaeast",
    "FR Central": "francecentral",
    "FR Central": "francecentral",
    "BR Southeast": "brazilsoutheast",
    "BR Southeast": "brazilsoutheast",
    "NO West": "norwaywest",
    "NO West": "norwaywest",
    "KR South": "koreasouth",
    "KR South": "koreasouth",
    "IN Central": "centralindia",
    "ZA West": "southafricawest",
    "NO East": "norwayeast",
    "UK South": "uksouth",
    "UK South": "uksouth",
    "AP Southeast": "southeastasia",
    "DE North": "germanynorth",
    "DE North": "germanynorth",
    "US South Central": "southcentralus",
    "AP East": "eastasia",
    "US North Central": "northcentralus",
    "US East": "eastus",
    "AP East": "eastasia",
    "AP East": "eastasia",
    "AU Central 2": "australiacentral2",
    "AU Central 2": "australiacentral2",
    "US West": "westus",
    "CA Central": "canadacentral",
    "EU West": "westeurope",
    "US Central": "centralus",
    "US Central": "centralus",
    "AU Southeast": "australiasoutheast",
    "AU Southeast": "australiasoutheast",
    "KR Central": "koreacentral",
    "KR Central": "koreacentral",
    "EU North": "northeurope",
    "EU North": "northeurope",
    "AP Southeast": "southeastasia",
    "AP Southeast": "southeastasia",
    "US West 2": "westus2",
    "US West 2": "westus2",
    "AE North": "uaenorth",
    "AE North": "uaenorth",
    "US West 2": "westus2",
    "CH North": "switzerlandnorth",
    "CH North": "switzerlandnorth",
    "IN Central": "centralindia",
    "IN Central": "centralindia",
    "NO East": "norwayeast",
    "NO East": "norwayeast",
    "IN South": "southindia",
    "KR Central": "koreacentral",
    "US Central": "centralus",
    "AE Central": "uaecentral",
    "DE West Central": "germanywestcentral",
    "DE West Central": "germanywestcentral",
    "BR South": "brazilsouth"
}